#!/bin/sh

if [ ! -d "build" ]; then
  mkdir build
fi

cd build

../sokol/shdc/linux/sokol-shdc --input ../shaders.glsl --output shaders.glsl.h --slang glsl330

gcc -fsanitize=address -g ../main.c -lX11 -lXi -lXcursor -lGL -lasound -ldl -lm -lpthread
