#!/bin/sh

if [ ! -d "build" ]; then
  mkdir build
fi

cd build

../sokol/shdc/linux/sokol-shdc --input ../shaders.glsl --output shaders.glsl.h --slang glsl330

clang ../main.c -I/usr/include/X11/extensions -fsanitize=address -O0 -g -lX11 -lXi -lXcursor -lGL -lasound -ldl -lm -lpthread
