#!/bin/sh

if [ ! -d "build" ]; then
  mkdir build
fi

cd build

../sokol/shdc/linux/sokol-shdc --input ../shaders.glsl --output shaders.glsl.h --slang glsl330

gcc -g ../main.c -lX11 -lXi -lXcursor -lGL -lasound -ldl -lm -lpthread
gcc -g -xc -Wall -Wextra -Werror -pedantic ../test_main.c -lX11 -lXi -lXcursor -lGL -lasound -ldl -lm -o test
cd ../
./build/test
rm ./build/test
